name: Java CI/CD with Maven and GKE

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [ '17' ]

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven Wrapper
        run: ./mvnw -B verify

      - name: Docker Hub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Container Image
        run: |
          ./mvnw spring-boot:build-image \
          -Dspring-boot.build-image.imageName=chandravishal07/petclinic:v1

      - name: Push Docker Image
        run: |
          docker push chandravishal07/petclinic:v1

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Install GKE Gcloud Auth Plugin
        run: |
          sudo apt-get update
          sudo apt-get install -y google-cloud-sdk-gke-gcloud-auth-plugin

      - name: Get GKE Credentials
        run: |
          gcloud container clusters get-credentials devops-cluster \
            --zone asia-south1-a

      - name: Deploy Database to GKE
        run: |
          kubectl apply -f k8s/db.yml -n petclinic

      - name: Deploy Application to GKE
        run: |
          kubectl apply -f k8s/petclinic.yml -n petclinic